version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      # Usa variável de ambiente MINIO_DATA_DIR, ou valor default
      - "${MINIO_DATA_DIR:-/mnt/data/minio}:/data"
    command: server /data --console-address ":9001"

networks:
  default:
    name: airflow-minio-net
