version: "3.8"

services:
  spark-master:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - USER=sparkuser
    ports:
      - "8888:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master Port
    mem_limit: 1g
    cpus: 1.0
    networks:
      - project-net
    volumes:
      - ./spark/jobs:/opt/jobs

  spark-worker-1:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - USER=sparkuser
    depends_on:
      - spark-master
    mem_limit: 1g
    cpus: 1.0
    networks:
      - project-net
    volumes:
      - ./spark/jobs:/opt/jobs

  spark:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark
    entrypoint: sleep infinity
    volumes:
      - ./spark/jobs:/opt/jobs
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - USER=sparkuser
    depends_on:
      - spark-master
    networks:
      - project-net

networks:
  project-net:
    driver: bridge
    name: project-net
    external: true