services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../config.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "${MINIO_DATA_DIR:-/mnt/data/minio}:/data"
    command: server /data --console-address ":9001"
    networks:
      - project-net

networks:
  project-net:
    external: true
